-- Migration 004: Move LoginAttemptTracker to database
-- Run in Supabase SQL Editor (Dashboard → SQL)

CREATE TABLE IF NOT EXISTS login_attempts (
    id bigint generated by default as identity primary key,
    username text NOT NULL,
    attempted_at timestamptz NOT NULL DEFAULT now(),
    success boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_login_attempts_user_time
    ON login_attempts (username, attempted_at DESC);

-- Lockouts table: tracks active lockouts
CREATE TABLE IF NOT EXISTS login_lockouts (
    username text PRIMARY KEY,
    locked_until timestamptz NOT NULL
);

-- Auto-cleanup: remove attempts older than 1 hour
-- (run periodically via Supabase cron or pg_cron)
-- DELETE FROM login_attempts WHERE attempted_at < now() - interval '1 hour';
-- DELETE FROM login_lockouts WHERE locked_until < now();
